services:
  server:
    build:
      context: ./server
    ports:
      - "3005:3005"

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
